version: "2"
services:
    web:
        build: ./web-image
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www:rw
        links:
            - db
        networks:
            - default
        hostname: http://hw0302.you-can-not-see-me.ninja/
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: PASSWORD_test
            MYSQL_ROOT_PASSWORD: ROOT_PASSWORD_test
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        networks:
            - default
        hostname: http://hw0302.you-can-not-see-me.ninja/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8082:80
        hostname: http://hw0302.you-can-not-see-me.ninja/
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: PASSWORD_test
            MYSQL_ROOT_PASSWORD: ROOT_PASSWORD_test